@Portfolio.ImageUploader_HostAddress = http://localhost:5231

### Upload image
POST {{Portfolio.ImageUploader_HostAddress}}/api/images
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./image.png
--boundary--
