services:
  - type: web
    name: image-uploader-service
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Portfolio.ImageUploader/Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_HTTP_PORTS
        value: "10000"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RABBITMQ_CONNECTION_STRING
        sync: false

  - type: web
    name: project-service
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Portfolio.Project/Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_HTTP_PORTS
        value: "10000"
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: project-db
          property: connectionString
      - key: RABBITMQ_CONNECTION_STRING
        sync: false
    databases:
      - name: project-db
        plan: free
        databaseName: project_service
        user: render_user
